name: Download Resume

on:
  push:
    branches:
      - main

jobs:
  download-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
        
    - name: Change directory
      run: cd static/files

    - name: Download file
      run: |
        curl -O https://raw.githubusercontent.com/xavierloeraflores/resume/main/resume.pdf

    - name: Configure Git
      run: |
        git config --global user.email "x.loera.tech@gmail.com"
        git config --global user.name "xavierloeraflores"

    - name: Commit & Push changes
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.GH_TOKEN_CLASSIC_LOERAFLORES_COM }}

    - name: Commit and push changes
      run: |
        git add .
        git commit -m "Downloaded file via GitHub Actions"
        git push https://${{ secrets.GH_TOKEN_CLASSIC_LOERAFLORES_COM }}@github.com/xavierloeraflores/resume.git HEAD:main
